# Generated by Django 5.1.7 on 2025-04-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sideimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SideImage',
        ),
    ]
