# Generated by Django 5.1.7 on 2025-04-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_itemvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariant',
            name='item_image',
            field=models.ImageField(upload_to='item_variants/'),
        ),
    ]
