# Generated by Django 5.1.7 on 2025-04-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_itemvariant_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sideimage',
            name='item_name',
            field=models.CharField(max_length=80),
        ),
    ]
