# Generated by Django 5.1.7 on 2025-05-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_itemvariant_item_name_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_bestSeller',
            field=models.BooleanField(default=False),
        ),
    ]
