# Generated by Django 5.1.7 on 2025-05-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_productmodel_is_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_newArrival',
            field=models.BooleanField(default=False),
        ),
    ]
