# Generated by Django 5.1.7 on 2025-05-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_productmodel_is_newarrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_size10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='is_size6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='is_size7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='is_size8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='is_size9',
            field=models.BooleanField(default=False),
        ),
    ]
