# Generated by Django 5.1.7 on 2025-05-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_productmodel_is_size10_productmodel_is_size6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='item_color',
            field=models.CharField(default='', max_length=80),
        ),
    ]
