# Generated by Django 5.1.7 on 2025-05-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_productmodel_item_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
