# Generated by Django 5.1.7 on 2025-05-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_productmodel_discount_delete_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='item_size',
            field=models.IntegerField(default=7),
        ),
    ]
