# Generated by Django 5.1.7 on 2025-05-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_cartmodel_item_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField(max_length=80)),
                ('payment_id', models.TextField(max_length=80)),
                ('amount', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
